algoritmo "Exemplo SE - Estrutura Condicional Simples - Operadores relacionais"
var
media: real
inicio


escreva("Digite a sua média: ")
leia(media)

// se a média for maior que 9 entao irá apresentar uma mensagem
// informando que ganhará o presente
// caso contrário, n ganhará
se (media > 9) entao
   escreval("Novo play station 2")
senao
   escreval("Sem PS2 :(, estude mais")
fimse

fimalgoritmo
